### ISSUE TITLE
Destroy/Reset method ?

### ISSUE THREAD

**Issue by alexandrebuffet** [CodyHouse/cd-diagonal-movement-changelog#1]
Hi ! 

What do you think about a destroy and reset method for this component ?

I found a pull request from the jQuery-menu-aim version about this functionality but it was never merged : https://github.com/kamens/jQuery-menu-aim/pull/41/files

I think it could be useful, in my case I'm trying to use it on a menu only in desktop version and I would like to delete/reset events on mobile.

**Comment by claudia-romano** [comment]
Hi Alexandre, thanks for the suggestion!
The plugin now includes two custom events you can use to reset your menu. You can read more here:
https://codyhouse.co/ds/components/info/diagonal-movement#reset-destroy

You can find the updated code here:
https://codyhouse.co/ds/components/app/diagonal-movement

Cheers!

**Comment by alexandrebuffet** [comment]
Thanks for the update!
